name: F3_SRP2
on:
  schedule:
    # Run every 8 minutes from 00:00 to 03:52 UTC
    - cron: '*/8 0-3 * * *'
    # Run at 04:00 UTC
    - cron: '0 4 * * *'

jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Set up Maven
        run: |
          sudo apt-get install -y maven
          
      - name: Build with Maven
        run: |
          mvn test
